# Generated by Django 5.2.15 on 2026-06-08 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_minute', models.PositiveSmallIntegerField()),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('card', 'Card'), ('penalty', 'Penalty')], max_length=20)),
                ('acting_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='league.team')),
                ('associated_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='accounts.player')),
            ],
            options={
                'ordering': ['match', 'timestamp_minute'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='league.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='league.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.season')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='CardEvent',
            fields=[
                ('matchevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matches.matchevent')),
                ('card_color', models.CharField(choices=[('yellow', 'Yellow'), ('red', 'Red')], max_length=10)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            bases=('matches.matchevent',),
        ),
        migrations.CreateModel(
            name='PenaltyEvent',
            fields=[
                ('matchevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matches.matchevent')),
                ('is_scored', models.BooleanField(default=False)),
                ('penalty_type', models.CharField(choices=[('in_game', 'In Game'), ('shootout', 'Shootout')], max_length=20)),
            ],
            bases=('matches.matchevent',),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match'),
        ),
        migrations.CreateModel(
            name='GoalEvent',
            fields=[
                ('matchevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matches.matchevent')),
                ('is_own_goal', models.BooleanField(default=False)),
                ('is_assisted', models.BooleanField(default=False)),
                ('assistant_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_goal_events', to='accounts.player')),
            ],
            bases=('matches.matchevent',),
        ),
    ]
