# Generated by Django 6.0.6 on 2026-06-22 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_possession', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('away_possession', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('home_shots', models.PositiveIntegerField(default=0)),
                ('away_shots', models.PositiveIntegerField(default=0)),
                ('home_shots_on_target', models.PositiveIntegerField(default=0)),
                ('away_shots_on_target', models.PositiveIntegerField(default=0)),
                ('home_touches', models.PositiveIntegerField(default=0)),
                ('away_touches', models.PositiveIntegerField(default=0)),
                ('home_passes', models.PositiveIntegerField(default=0)),
                ('away_passes', models.PositiveIntegerField(default=0)),
                ('home_tackles', models.PositiveIntegerField(default=0)),
                ('away_tackles', models.PositiveIntegerField(default=0)),
                ('home_clearances', models.PositiveIntegerField(default=0)),
                ('away_clearances', models.PositiveIntegerField(default=0)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='matches.match')),
            ],
        ),
    ]
