# Generated by Django 6.0.6 on 2026-07-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_matchstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('half_time', 'Half Time'), ('completed', 'Full Time')], default='upcoming', max_length=20),
        ),
    ]
