# Generated by Django 5.2.15 on 2026-06-06 14:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_minute', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['match', 'timestamp_minute'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('president', 'President'), ('player', 'Player'), ('admin', 'Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SecretCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('1v1_mode', '1v1 Mode'), ('double_goals', 'Double Goals'), ('instant_penalty', 'Instant Penalty')], max_length=30)),
                ('is_revealed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardEvent',
            fields=[
                ('matchevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.matchevent')),
                ('card_type', models.CharField(choices=[('yellow', 'Yellow'), ('red', 'Red')], max_length=10)),
            ],
            bases=('core.matchevent',),
        ),
        migrations.CreateModel(
            name='GoalEvent',
            fields=[
                ('matchevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.matchevent')),
                ('is_own_goal', models.BooleanField(default=False)),
            ],
            bases=('core.matchevent',),
        ),
        migrations.CreateModel(
            name='PenaltyEvent',
            fields=[
                ('matchevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.matchevent')),
                ('outcome', models.CharField(choices=[('scored', 'Scored'), ('missed', 'Missed'), ('saved', 'Saved')], max_length=10)),
            ],
            bases=('core.matchevent',),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.match'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('position', models.CharField(max_length=50)),
                ('draft_status', models.CharField(choices=[('available', 'Available'), ('drafted', 'Drafted'), ('undrafted', 'Undrafted')], default='available', max_length=20)),
                ('skill_rating', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('social_media_channel', models.URLField(blank=True)),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('standings_table', models.JSONField(blank=True, default=dict)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.league')),
            ],
            options={
                'ordering': ['-season_number'],
                'unique_together': {('league', 'season_number')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.season'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo_url', models.URLField(blank=True)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.season')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('season', 'name')},
            },
        ),
        migrations.AddField(
            model_name='matchevent',
            name='acting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team'),
        ),
        migrations.CreateModel(
            name='CardActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_minute', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_activations', to='core.match')),
                ('secret_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='core.secretcard')),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_activations', to='core.team')),
            ],
            options={
                'ordering': ['match', 'activation_minute'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('mvp_awards', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.player')),
            ],
            options={
                'verbose_name_plural': 'player stats',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.team'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='associated_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='core.player'),
        ),
        migrations.AddField(
            model_name='secretcard',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_cards', to='core.president'),
        ),
        migrations.AddField(
            model_name='president',
            name='associated_team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president', to='core.team'),
        ),
    ]
