# Generated by Django 5.2.15 on 2026-06-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardActivation',
        ),
        migrations.DeleteModel(
            name='CardEvent',
        ),
        migrations.DeleteModel(
            name='GoalEvent',
        ),
        migrations.DeleteModel(
            name='PenaltyEvent',
        ),
        migrations.DeleteModel(
            name='MatchEvent',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='President',
        ),
        migrations.DeleteModel(
            name='SecretCard',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
