# Generated by Django 5.2.15 on 2026-06-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_cardevent_matchevent_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='posters/')),
                ('target_url', models.URLField(blank=True, help_text='Optional link when the poster is clicked', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this poster should be featured on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Special Poster',
                'verbose_name_plural': 'Special Posters',
            },
        ),
    ]
