# Generated by Django 6.0.6 on 2026-06-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_disciplinerule_entertainmentfeature_rulecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerule',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='gamerule',
            options={},
        ),
        migrations.AlterField(
            model_name='gamerule',
            name='punishment',
            field=models.TextField(blank=True, help_text='Use each point on a new line'),
        ),
        migrations.AlterField(
            model_name='gamerule',
            name='special_rule',
            field=models.TextField(blank=True, help_text='Use each point on a new line'),
        ),
        migrations.DeleteModel(
            name='RuleCategory',
        ),
    ]
