# Generated by Django 5.2.15 on 2026-06-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_remove_league_country_team_draws_team_games_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Mark this as the current live season'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
