# Generated by Django 6.0.6 on 2026-06-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_remove_team_logo_url_season_is_active_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='foundation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='total_titles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
