# Generated by Django 5.2.15 on 2026-06-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_team_facebook_url_team_foundation_year_team_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
