# Generated by Django 6.0.6 on 2026-06-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_covers/'),
        ),
    ]
