# Generated by Django 6.0.6 on 2026-06-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='player_profiles/'),
        ),
    ]
