# Generated by Django 6.0.6 on 2026-06-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_player_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True, help_text='Player bio or description displayed on the profile page.', null=True),
        ),
    ]
