# Generated by Django 5.2.15 on 2026-06-08 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('1v1_mode', '1v1 Mode'), ('double_goals', 'Double Goals'), ('instant_penalty', 'Instant Penalty'), ('remove_opponent', 'Remove Opponent')], max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_minute', models.PositiveSmallIntegerField()),
                ('is_exhausted', models.BooleanField(default=False)),
                ('activating_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_activations', to='league.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_activations', to='matches.match')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='cards.secretcard')),
            ],
            options={
                'ordering': ['match', 'activation_minute'],
            },
        ),
    ]
